version: '3.8'

services:
  logistics-db:
    image: postgres:14
    container_name: logistics-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logistics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logistics-network

networks:
  logistics-network:
    external: true

volumes:
  postgres_data: