version: '3.8'

services:
  test-db:
    image: postgres:14
    container_name: test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_logistics
    ports:
      - "5432:5432"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge